version: "2"
languages:
  TypeScript: true
  JavaScript: true
plugins:
  eslint:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
ratings:
  paths:
  - "**.js"
  - "**.ts"
  - "**.css"
exclude_paths:
- "unit-tests/"
- "protractor/"
- ".*"
- "web-server/*.config.js"
