version: "2"
languages:
  TypeScript: true
  JavaScript: true
plugins:
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
  tslint:
    enabled: true
    config: tslint.yaml
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.ts"
  - "**.css"
  - "**.scss"
exclude_paths:
- "protractor/"
- ".*"
