sudo: false
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
  - "node"
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- bin/json-lint.sh
- npm run test
<<<<<<< HEAD
- npm run e2e-test
=======
- NODE_ENV=prod npm run heroku-postbuild
>>>>>>> ddb4694635dac95afda15fc6be6dd4d5954b14b6
notifications:
  email: false
  slack:
    secure: CqCIWOL6adhpkwxhpbEWec7zSd/XAFvDKLzDDWb2Yu2pcqSIavocv95gH1Uxf5Bp8TA6xNaVSs2TmWf9MGn5sC2OB6U8oXqdgPmiAFjvPjM9ismITr0oLecdAfJfK7oVizL/P1CI1gddfEZjq6N/hkD/el+6lRgApB2+E+oldJU=
